os.sleep(1)
term.clear()
term.setCursorPos(1, 1)
print("This is used for hacking.")
print("10, Ryan,")
print("56, Cheesy,")
print("31, Chris,")
print("16, Jeremy,")
print("40, Hunter,")
print("73, Chris's basement,")
print("83, Chris's hacking tablit")